server:
  port: ${PERSON_SERVER_PORT}

spring:
  application:
    name: person
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://${DB_HOST}:${DB_PORT};databaseName=${DB_NAME};encrypt=${DB_ENCRYPT};trustServerCertificate=${DB_TRUST_SERVER_CERT}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: ${SPRING_JPA_SHOW_SQL}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        default_schema: dbo

flyway:
  enabled: true
  locations: classpath:db/migration
  schemas: dbo
  table: flyway_schema_history_person
  baseline-on-migrate: true

jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}
  roles-claim: role
  expiration: ${JWT_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
