spring:
  datasource:
    url: jdbc:sqlserver://${DB_HOST:localhost}:${DB_PORT:1433};databaseName=${DB_NAME:crmdb}
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:StrongPassword12345}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
