server:
  port: ${TICKET_SERVICE_PORT}

spring:
  application:
    name: ticket-service

  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://${DB_HOST}:${DB_PORT};databaseName=${DB_NAME};encrypt=${DB_ENCRYPT};trustServerCertificate=${DB_TRUST_SERVER_CERT}
    username: ${DB_USER}
    password: ${DB_PASSWORD:${MSSQL_SA_PASSWORD}}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: ${SPRING_JPA_SHOW_SQL}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        default_schema: dbo

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: dbo
    table: flyway_schema_history_ticket
    baseline-on-migrate: true

jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}
  roles-claim: role

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

